config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations",
    passwords: "user/passwords",
  }

  root :to => "backend/home#index"

  namespace :backend do
    get '/' => 'home#index'

  mount UeditorRails::Engine => '/ueditor'

    resources :catalogs
    resources :home_page
    resources :pictures
    resources :abouts do
      collection do
        get :edit_detail
      end
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  
end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  belongs_to :avatarable, :polymorphic => true
  mount_uploader :photo, AvatarUploader

  def is_image
    str = self.photo.path.split(".").last
    image_type = "bmp,jpg,jpeg,png,tiff,gif,pcx,tga,exif,fpx,svg,psd,cdr,pcd,dxf,ufo,eps,ai,raw"
    if image_type.include?(str)
      return true
    else
      return false
    end
  end
end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  has_many :articles
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_many :avatars, :as => :avatarable,dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backend/abouts_controller.rb
class Backend::AboutsController < ApplicationController
	layout 'spp'
        
  def index
    if params[:item] == "3"
     @cotent = About.first.contact
   elsif params[:item] == "2"
    @cotent = About.first.recruit
   else 
    @cotent = About.first.synopsis
   end
  end

  def edit_detail
    @about = About.first
    @item = params[:item]
  end

  def update
    @about = About.first
    @about.update_attributes(about_params)
    redirect_to :action => :index
  end

   private			
  def about_params
     params.require(:about).permit(:synopsis, :recruit, :contact, :id)
  end
end

app/controllers/backend/articles_controller.rb
class Backend::ArticlesController < Backend::BaseController

  def index
  end

end

app/controllers/backend/base_controller.rb
class Backend::BaseController < ActionController::Base

	layout "spp"
	
end

app/controllers/backend/catalogs_controller.rb
class Backend::CatalogsController <  Backend::BaseController
  
  def index
    @catalogs = Catalog.all.order("id desc").page(params[:page]).per(20)
  end

  def new
    @catalog = Catalog.new
  end

  def create
    @catalog = Catalog.new(catalog_params)
    if @catalog.save
      redirect_to backend_catalogs_path(:back => request.fullpath)
   else
     render "new"
    end
  end

  def edit
    @catalog = Catalog.find(params[:id])
  end

 
  def update
    catalog = Catalog.find(params[:id])
    if catalog.update_attributes(catalog_params)
      flash[:success] = '更新成功!'
      @catalogs = Catalog.all
      render 'index'
    else
      flash[:error] = '更新失败!'
      redirect_to :back
    end
  end

  # before_filter  do
  #   binding.pry
  # end


  def destroy
    @catalog = Catalog.find(params[:id])
    @catalog.destroy
     redirect_to  backend_catalogs_path
  end

 def show
    @catalog = Catalog.find(params[:id])
  end

  private
    def catalog_params
      params.require(:catalog).permit(:name, :desc)
    end

end

app/controllers/backend/home_controller.rb
class Backend::HomeController <   Backend::BaseController
before_filter :authenticate_user!
  def index
  	
  end
end

app/controllers/backend/home_page_controller.rb
class Backend::HomePageController < ActionController::Base
layout 'spp'
before_filter :authenticate_user!
  def index
  	
  end
end

app/controllers/backend/pictures_controller.rb
class Backend::PicturesController < ActionController::Base
layout 'spp'
before_filter :authenticate_user!
before_filter :find_picture
  def index
    @pictures = Picture.all	
  end

  def new
    @picture = Picture.new 	
  end

  def create
    @picture = Picture.new(picture_params)
     if @picture.save
      @picture.avatars.create(:photo => params[:photo])
      redirect_to backend_pictures_path(:back => request.fullpath)
    else
      render 'new'   	
    end
  end

  def edit

  end

  def update
    @picture.update_attributes(picture_params)
     if params[:photo]
         @picture.avatars.each do |ta|
          ta.update(:photo => params[:photo])
         end
     end  
    redirect_to backend_pictures_path(:back => request.fullpath) 

  end

  def destroy
    @picture.destroy
    redirect_to backend_pictures_path
  end
  private
  def find_picture
     @picture = Picture.find(params[:id]) if params[:id]
  end

  def picture_params
     params.require(:picture).permit(:name)
   end	
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index

  end

end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController

end

app/helpers/application_helper.rb
module ApplicationHelper

   def index_no(index,per)
    params[:page] ||= 1
    (params[:page].to_i - 1) * per + index + 1
  end

   def plate_link(path, options)
    color = options[:color] ||= 'red'
    is_first = options[:is_first] ||= false
    s_class = !is_first ? 'publicplate' : 'fristplate'
    link_to path do
      %Q|
        <li>
        <div class="#{s_class} #{color}">
          <h2>#{options[:title]}</h2>
          <p>#{options[:desc]}</p>
        </div>
        </li>
      |.html_safe
    end
   end

   def markdown(text)
    coderayified = CodeRayify.new(:filter_html => true, 
                                  :hard_wrap => true)
    options = {
      :fenced_code_blocks => true,
      :no_intra_emphasis => true,
      :autolink => true,
      :strikethrough => true,
      :lax_html_blocks => true,
      :superscript => true
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end

end

app/views/backend/catalogs/_form.html.erb
<%= form_for [:backend,@catalog], html: {:class => "valid_engine establish"} do |f| %>
  <div class="public_form">
    <label class="label"><span></span>栏目名称：</label>
    <%= f.text_field :name%>
  </div>

  <div class="public_form">
    <label class="label"><span></span>栏目描述：</label>
    <%= f.text_area :desc%>
  </div>

  <div>
   <%= render '/backend/shared/form_buttons',:f => f %>
  </div>

<% end -%>

app/views/backend/catalogs/edit.html.erb
<h1>编辑栏目</h1>
<%= render :partial => 'form' %>

app/views/backend/catalogs/index.html.erb
<div class="plate">
  <ul>
    <%= plate_link new_backend_catalog_path(:back => request.fullpath), is_first:true, color:'red', title:'添加栏目', desc:'添加栏目'%>
  </ul>
</div>
<h1>栏目分类列表<%= link_to '返回', params[:back], class: "ml8" unless params[:back].blank? %></h1>

<div class="well_head">
  <div class="jianju_x"></div>
  <table class="common" >
    <tbody>
      <tr>
        <td>序号</td>
        <td>名称</td>
        <td>操作</td>
      </tr>
      <% @catalogs.each_with_index do|catalog,index|%>
        <tr>
          <td><%= index_no(index,20)%></td>
          <td><%= catalog.name%></td>
          <td class="textc operation">
            <%= link_to "修改", edit_backend_catalog_path(catalog, :back => request.fullpath) %>
            <%= link_to '删除', backend_catalog_path(catalog, :back => request.fullpath), :method => :delete, data:{confirm: "确定要删除吗？"}%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/backend/catalogs/new.html.erb
<h1>添加栏目</h1>
<%= render :partial => 'form' %>

app/views/backend/catalogs/show.html.erb
<% list_link = backend_catalogs_path(:back => request.fullpath) %>

<h1>
  <%= "#{@catalog.try(:name)}"%>栏目详情：

  <%= link_to '返回', params[:back] || list_link %>
</h1>

  <%= link_to '修改', edit_backend_catalog_path(@catalog, :back => request.fullpath)%>


<div class="well_head">
  <div class="jianju_x"></div>

  <div class='mb20 document_content'>
    <%= markdown(@catalog.desc) rescue nil%>
  </div>
</div>

app/views/backend/home_page/index.html.erb
  <div class="plate">
    <ul>
      <%= plate_link backend_pictures_path, is_first: true, color: 'red', title: '图片管理', desc: '管理图片' %>
    </ul>
  </div>
  <div class="line"></div>  

app/views/backend/pictures/_form.html.erb
<%= form_for [:backend,@picture], html: {:class => "valid_engine establish", multipart: true} do |f| %>
  <div class="public_form">
    <label class="label"><span>*</span>图片名称:</label>
    <%= f.text_field :name, class: 'validate[required] public_input' %>
  </div>

  <div class="public_form">
    <label class="label">图片上传</label>
    <%= file_field_tag :photo, class: "face" %>
    <% if not @picture.avatars.nil? %>
      <% @picture.avatars.each do |ta|%>
        <a class="pic" href="<%= ta.photo.url %>" ><%= image_tag(ta.photo.url, size: "100x80", title: '点击放大') %></a>
      <% end %>
    <% end %>
  </div>
    <%= render '/backend/shared/form_buttons', :f => f  %>
<% end %>

app/views/backend/pictures/edit.html.erb
<%= render 'form' %>

app/views/backend/pictures/index.html.erb
<div class="plate">
    <ul>
      <%= plate_link new_backend_picture_path(:back => request.fullpath), is_first: true, color: 'green', title: '新增图片', desc: '添加图片' %>
    </ul>
  </div>
  <div class="line"></div> 
<div class="well_head">
  <table class="common">
    <tbody>
      <tr>
        <td>图片名称</td>
        <td>图片内容</td>
        <td>操作</td>
      </tr>

      <% @pictures.each do |picture| %>
        <tr>
         <td><%=picture.name%></td>
         <td>
           <% picture.avatars.each do |ta|%>
             <a class="pic" href="<%= ta.photo.url %>" ><%= image_tag(ta.photo.url, size: "100x80", title: '点击放大') %></a>
          <% end %>
         </td>
         <td>
         <%= link_to '查看', backend_picture_path(picture, :back => request.fullpath)%>
         <%= link_to '修改', edit_backend_picture_path(picture, :back => request.fullpath)%>
         <%= link_to '删除', backend_picture_path(picture, :back => request.fullpath), data: {method: :delete,confirm: "你确定删除?"} %>
         </td>
       </tr>

      <% end %>
      <td class="textc operation">  
      </td>
    </tbody>
  </table>
</div>

app/views/backend/pictures/new.html.erb
<h1>新建图片</h1>
<%= render 'form' %>

app/views/backend/pictures/show.html.erb
<h1>详情</h1>
<div class="well_head">

  <div class="establish">
   <div class="public_form">
      <label class="label">图片名称:</label>
      <span class="validate-name"><%= @picture.name %></span>
    </div>

    <div class="public_form">
      <label class="label">图片内容:</label>
      <span class="validate-name">
        <% @picture.avatars.each do |ta|%>
             <a class="pic" href="<%= ta.photo.url %>" ><%= image_tag(ta.photo.url, size: "100x80", title: '点击放大') %></a>
          <% end %>
      </span>
    </div> 

  <%= link_to '修改', edit_backend_picture_path(@picture, :back => request.fullpath)%>
  <%= link_to '返回', params[:back]  %>
  </div>
</div>

app/views/backend/shared/_form_buttons.html.erb
<% html ||="" %>
<div class="form-actions tc">
  <%= hidden_field_tag 'back', params[:back] %>
  <%= f.button "提交", :class => "submit submit_blue mt10 w50 ml100"%>
  <%= link_to "返回", params[:back], class: 'submit submit_gray mt10 w50' if params[:back].present? %>
  <%= html.html_safe%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/spp.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>阳光公采网站管理系统</title>
    <%= stylesheet_link_tag 'spp', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'spp', 'data-turbolinks-track' => true %>
  </head>
  <body>

    <!--左侧代码开始-->
    <div class="project-left">
      <div class="logo">
        <h1><span>网站管理系统</span></h1>
      </div>
      <div class="left_nav">
        <ul>
          <!-- li class="nav_other"><li -->
            <li><%= link_to "管理员设置",  edit_user_registration_path %></li>
            <li> <%=link_to '首页', backend_home_page_index_path %></li>
            <li> <a href="">资讯动态 </a></li>
            <li> <a href="">产品与方案 </a></li>
            <li> <a href="">文章及栏目管理 </a></li>
            <li> <a href="">关于我们 </a></li>

        </ul>
      </div>
    </div>
    <!--左侧代码结束-->

    <!--右侧代码开始-->
    <div class="project-right">

      <!--个人信息代码开始-->
      <div class="personal">

        <div class="personal_left">

          <div class="personal_name">
            <h2>Hello，</h2>
            <p>欢迎光临阳光公采网站管理系统！
            </p>
          </div>
        </div>
         <%=link_to "登出", destroy_user_session_path,class: "close"%>
      </div>
      <!--个人信息代码结束-->

      <div class='container'>
        <div class="content">
          <%= yield %>
        </div>

      </div>

    </div>


  </body>
</html>